version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:3.6.2
    volumes:
      - /data/db
    ports:
      - "27017"

  #reviews:
    #container_name: reviews
    #restart: always
    #build: /Users/dmp/hr/immersive/fec/reviews
    #ports:
      #- "8001"
    #links:
      #- mongo
    #command: npm start
  reviews:
    container_name: reviews
    restart: always
    image: dpaikoff/hrsf89_fec:reviews1
    ports:
      - "8001"
    links:
      - mongo
    command: npm start

  menus:
    container_name: menus
    restart: always
    image: jqywang/opentable-menu:menu1
    ports:
      - "8000"
    links:
      - mongo
    command: npm start

  photos:
    container_name: photos
    restart: always
    image: leesuehee/opentable_photos:photo1
    ports:
      - "8002"
    links:
      - mongo
    command: npm start

  proxy:
    container_name: proxy
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - reviews
